export const STATUS_LIST_REQUEST = "STATUS_LIST_REQUEST";
export const STATUS_LIST_SUCCESS = "STATUS_LIST_SUCCESS";
export const STATUS_LIST_FAIL = "STATUS_LIST_FAIL";

export const STATUS_LIST_OWNER_REQUEST = "STATUS_LIST_OWNER_REQUEST";
export const STATUS_LIST_OWNER_SUCCESS = "STATUS_LIST_OWNER_SUCCESS";
export const STATUS_LIST_OWNER_FAIL = "STATUS_LIST_OWNER_FAIL";
export const STATUS_LIST_OWNER_RESET = "STATUS_LIST_OWNER_RESET";

export const STATUS_DETAILS_REQUEST = "STATUS_DETAILS_REQUEST";
export const STATUS_DETAILS_SUCCESS = "STATUS_DETAILS_SUCCESS";
export const STATUS_DETAILS_FAIL = "STATUS_DETAILS_FAIL";

export const STATUS_DELETE_REQUEST = "STATUS_DELETE_REQUEST";
export const STATUS_DELETE_SUCCESS = "STATUS_DELETE_SUCCESS";
export const STATUS_DELETE_FAIL = "STATUS_DELETE_FAIL";
export const STATUS_DELETE_RESET = "STATUS_DETAILS_RESET";

export const STATUS_CREATE_REQUEST = "STATUS_CREATE_REQUEST";
export const STATUS_CREATE_SUCCESS = "STATUS_CREATE_SUCCESS";
export const STATUS_CREATE_FAIL = "STATUS_CREATE_FAIL";
export const STATUS_CREATE_RESET = "STATUS_CREATE_RESET";

export const STATUS_UPDATE_REQUEST = "STATUS_UPDATE_REQUEST";
export const STATUS_UPDATE_SUCCESS = "STATUS_UPDATE_SUCCESS";
export const STATUS_UPDATE_FAIL = "STATUS_UPDATE_FAIL";
export const STATUS_UPDATE_RESET = "STATUS_UPDATE_RESET";

export const STATUS_CREATE_COMMENT_REQUEST = "STATUS_CREATE_COMMENT_REQUEST";
export const STATUS_CREATE_COMMENT_SUCCESS = "STATUS_CREATE_COMMENT_SUCCESS";
export const STATUS_CREATE_COMMENT_FAIL = "STATUS_CREATE_COMMENT_FAIL";
export const STATUS_CREATE_COMMENT_RESET = "STATUS_CREATE_COMMENT_RESET";
