# Generated by Django 3.1.7 on 2021-05-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHATI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='start',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
