# Generated by Django 3.1.7 on 2021-05-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHATI', '0002_auto_20210526_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
