# Generated by Django 3.1.7 on 2021-06-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHATI', '0004_auto_20210526_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
